# Generated by Django 4.1 on 2023-08-11 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.products.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Category name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Category slug",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                        verbose_name="Category parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("sku", models.CharField(max_length=255, verbose_name="Product sku")),
                ("name", models.CharField(max_length=255, verbose_name="Product name")),
                (
                    "brand",
                    models.CharField(max_length=255, verbose_name="Product brand"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=11, verbose_name="Product price"
                    ),
                ),
                (
                    "wholesale_quantity",
                    models.PositiveIntegerField(verbose_name="Product wholesale quantity"),
                ),
                (
                    "video",
                    models.FileField(
                        null=True,
                        upload_to=apps.products.models.get_product_directory_path,
                        verbose_name="Product video",
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.PositiveIntegerField(verbose_name="Products quantity in stock"),
                ),
                ("description", models.TextField(verbose_name="Product description")),
                (
                    "manufacturer_country",
                    models.CharField(max_length=255, verbose_name="Product manufacturer country"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="products.category",
                        verbose_name="Product category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Product supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to=apps.products.models.get_product_directory_path,
                        verbose_name="Product image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_pr_categor_9edb3d_idx"),
        ),
    ]
