# Generated by Django 4.1 on 2023-08-13 14:23

from django.db import migrations, models

import apps.products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.products.models.get_product_directory_path,
                verbose_name="Product video",
            ),
        ),
    ]
