# Generated by Django 4.1 on 2023-08-29 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=11,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Product price",
            ),
        ),
    ]
