# Generated by Django 4.1 on 2023-08-17 22:15

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="video",
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.products.models.get_product_directory_path,
                        verbose_name="Product video",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
        ),
    ]
