# Generated by Django 4.1 on 2023-08-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.products.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_alter_product_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suppliers",
                to=settings.AUTH_USER_MODEL,
                validators=[apps.products.models.validate_user],
                verbose_name="Product supplier",
            ),
        ),
    ]
