# Generated by Django 4.1 on 2023-09-01 22:09

import django.db.models.deletion
from django.db import migrations, models

import apps.products.models
import apps.products.validators


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="video",
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.products.models.get_product_directory_path,
                        validators=[
                            apps.products.validators.VideoValidator(
                                content_types=("video/mp4", "video/webm"), max_size=3145728
                            )
                        ],
                        verbose_name="Product video",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
    ]
