# Generated by Django 4.1 on 2023-08-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_products",
            field=models.ManyToManyField(
                related_name="order_products",
                through="orders.OrderProduct",
                to="products.product",
                verbose_name="Products",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
    ]
