version: "3.8"
volumes:
  pg_data:

services:
  db:
    image: postgres:15.3
    container_name: b2b-marketplace-db-local
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ../
      dockerfile: infra/Dockerfile.dev
    container_name: b2b-marketplace-backend
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py createsuperuser --no-input --username admin --email admin@example.com &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
