FROM python:3.10-slim-bookworm

RUN python -m pip install --upgrade pip

WORKDIR /b2b_marketplace

COPY poetry.lock pyproject.toml ./

RUN pip install poetry==1.5.1
RUN poetry config virtualenvs.create false
RUN poetry install

COPY . .
