FROM python:3.11-slim

RUN python -m pip install --upgrade pip
RUN pip install poetry

WORKDIR /app

COPY ../pyproject.toml ../poetry.lock /app/

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY . /app/
