# Generated by Django 4.1 on 2023-08-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("baskets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="basket_products",
            field=models.ManyToManyField(
                through="baskets.BasketProduct", to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="basketproduct",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket",
                to="baskets.basket",
                verbose_name="Basket",
            ),
        ),
    ]
