# Generated by Django 4.1 on 2023-08-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_video"),
        ("baskets", "0002_basket_basket_products_alter_basketproduct_basket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="basket_products",
            field=models.ManyToManyField(
                related_name="basket_products",
                through="baskets.BasketProduct",
                to="products.product",
            ),
        ),
    ]
