# Generated by Django 4.1 on 2023-08-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.baskets.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("baskets", "0003_alter_basket_basket_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                validators=[apps.baskets.models.validate_user_is_buyer],
                verbose_name="User",
            ),
        ),
    ]
