# Generated by Django 4.1 on 2023-08-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.phonenumber"
            ),
        ),
        migrations.AlterField(
            model_name="physicalperson",
            name="phone_number",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.phonenumber"
            ),
        ),
    ]
