# Generated by Django 4.1 on 2023-08-14 16:43

from django.db import migrations

import apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", apps.users.models.CustomUserManager()),
            ],
        ),
    ]
