# Generated by Django 4.1 on 2023-08-16 04:56

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_account",
            field=models.CharField(
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    apps.users.models.validate_account,
                    apps.users.models.validate_digits_only,
                ],
                verbose_name="Account",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="ogrn",
            field=models.CharField(
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    apps.users.models.validate_ogrn,
                    apps.users.models.validate_digits_only,
                ],
                verbose_name="PSRN",
            ),
        ),
    ]
