# Generated by Django 4.1 on 2023-08-16 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_address_options_alter_address_address_and_more"),
        ("users", "0003_alter_company_company_account_alter_company_ogrn"),
    ]

    operations = []
