# Generated by Django 4.1 on 2023-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_video"),
        ("users", "0005_alter_company_company_account_alter_company_ogrn"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="favourited_by",
                to="products.product",
                verbose_name="Favorite products",
            ),
        ),
    ]
