# Generated by Django 4.1 on 2023-09-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_company_vat"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
