# Generated by Django 4.1 on 2023-09-08 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0006_customuser_favorite_products"),
        ("orders", "0005_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("delivery_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
            },
        ),
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Delivery method name"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Delivery method description"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Delivery method slug"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=11,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Delivery price",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery method",
                "verbose_name_plural": "Delivery methods",
            },
        ),
        migrations.AddIndex(
            model_name="deliverymethod",
            index=models.Index(fields=["slug"], name="deliveries__slug_4017c1_idx"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="delivery_address",
                to="users.address",
                verbose_name="Delivery address",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="delivery_method",
                to="deliveries.deliverymethod",
                verbose_name="Delivery method",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="delivery_order",
                to="orders.order",
                verbose_name="Delivery order",
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["order"], name="deliveries__order_i_3c4f0e_idx"),
        ),
    ]
