# Generated by Django 4.1 on 2023-10-05 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_remove_orderproduct_discount_orderproduct_price_and_more"),
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="delivery_order",
                to="orders.order",
                verbose_name="Delivery order",
            ),
        ),
    ]
